myNextApplication:
  component: '@sls-next/serverless-component@latest'
  name: 'alpoxdev-client'
  inputs:
    publicDirectoryCache:
      value: public, max-age=604800
      test: /\.(gif|jpe?g|png|txt|xml)$/i
